using Microsoft.EntityFrameworkCore;

public static class Dashboard
{
    public static void Run(CatalogDbContext db)
    {
        Console.WriteLine();
        Console.WriteLine("EF Core translates LINQ to SQL before materializing the results.");

        Render(
            "1. Products with their categories",
            CatalogQueries.ProductsWithCategories(db),
            result => $"{result.ProductName} | {result.CategoryName} | {result.Price:C} | stock: {result.StockQuantity}");

        Render(
            "2. Search products containing 'Code'",
            CatalogQueries.SearchProducts(db, "Code"),
            result => $"{result.ProductName} | {result.CategoryName} | {result.Price:C} | stock: {result.StockQuantity}");

        Render(
            "3. Product count by category",
            CatalogQueries.CategoryProductCounts(db),
            result => $"{result.CategoryName} | products: {result.ProductCount}");

        Render(
            "4. Inventory value by category",
            CatalogQueries.CategoryInventoryTotals(db),
            result => $"{result.CategoryName} | inventory value: {result.InventoryValue:C}");
    }

    private static void Render<TResult>(
        string title,
        IQueryable<TResult> query,
        Func<TResult, string> format)
    {
        Console.WriteLine();
        Console.WriteLine(new string('=', 72));
        Console.WriteLine(title);
        Console.WriteLine(new string('-', 72));
        Console.WriteLine("SQL generated by EF Core:");
        Console.WriteLine(query.ToQueryString());
        Console.WriteLine("Results:");

        foreach (var result in query)
        {
            Console.WriteLine($"- {format(result)}");
        }
    }
}
