using Microsoft.EntityFrameworkCore;

public static class Dashboard
{
    public static void Run(CatalogDbContext db)
    {
        while (true)
        {
            Console.WriteLine();
            WriteLine(ConsoleColor.Cyan, "Choose an operation:");
            WriteLine(ConsoleColor.Cyan, "1. Products with their categories");
            WriteLine(ConsoleColor.Cyan, "2. Search products containing 'Code'");
            WriteLine(ConsoleColor.Cyan, "3. Product count by category");
            WriteLine(ConsoleColor.Cyan, "4. Inventory value by category");
            WriteLine(ConsoleColor.Cyan, "5. Show EF Core execution pipeline");
            WriteLine(ConsoleColor.Cyan, "0. Exit");
            Write(ConsoleColor.Yellow, "Selection: ");

            switch (Console.ReadLine())
            {
                case "1":
                    Render(
                        "1. Products with their categories",
                        "db.Products.OrderBy(product => product.Category.Name).Select(product => new { product.Name, Category = product.Category.Name, product.Price, product.StockQuantity })",
                        CatalogQueries.ProductsWithCategories(db),
                        result => $"{result.ProductName} | {result.CategoryName} | {result.Price:C} | stock: {result.StockQuantity}");
                    break;
                case "2":
                    Render(
                        "2. Search products containing 'Code'",
                        "db.Products.Where(product => product.Name.Contains('Code')).OrderBy(product => product.Name).Select(product => new { product.Name, Category = product.Category.Name, product.Price, product.StockQuantity })",
                        CatalogQueries.SearchProducts(db, "Code"),
                        result => $"{result.ProductName} | {result.CategoryName} | {result.Price:C} | stock: {result.StockQuantity}");
                    break;
                case "3":
                    Render(
                        "3. Product count by category",
                        "db.Categories.OrderBy(category => category.Name).Select(category => new { category.Name, ProductCount = category.Products.Count() })",
                        CatalogQueries.CategoryProductCounts(db),
                        result => $"{result.CategoryName} | products: {result.ProductCount}");
                    break;
                case "4":
                    Render(
                        "4. Inventory value by category",
                        "db.Categories.OrderBy(category => category.Name).Select(category => new { category.Name, InventoryValue = category.Products.Sum(product => product.Price * product.StockQuantity) })",
                        CatalogQueries.CategoryInventoryTotals(db),
                        result => $"{result.CategoryName} | inventory value: {result.InventoryValue:C}");
                    break;
                case "5":
                    ExpressionTreeRenderer.Render(CatalogQueries.ProductsWithCategoriesWithFilter(db));
                    break;
                case "0":
                    Console.ResetColor();
                    return;
                default:
                    WriteLine(ConsoleColor.Red, "Invalid selection. Choose 0, 1, 2, 3, 4, or 5.");
                    break;
            }
        }
    }

    private static void Render<TResult>(
        string title,
        string linqQuery,
        IQueryable<TResult> query,
        Func<TResult, string> format)
    {
        Console.WriteLine();
        WriteLine(ConsoleColor.DarkCyan, new string('=', 72));
        WriteLine(ConsoleColor.Cyan, title);
        WriteLine(ConsoleColor.DarkCyan, new string('-', 72));
        WriteLine(ConsoleColor.Yellow, "LINQ query:");
        WriteLine(ConsoleColor.Yellow, linqQuery);
        Console.WriteLine();
        WriteLine(ConsoleColor.DarkGray, "SQL generated by EF Core:");
        WriteLine(ConsoleColor.DarkGray, query.ToQueryString());
        WriteLine(ConsoleColor.Green, "Results:");

        foreach (var result in query)
        {
            WriteLine(ConsoleColor.Green, $"- {format(result)}");
        }
    }

    private static void Write(ConsoleColor color, string value)
    {
        Console.ForegroundColor = color;
        Console.Write(value);
        Console.ResetColor();
    }

    private static void WriteLine(ConsoleColor color, string value)
    {
        Console.ForegroundColor = color;
        Console.WriteLine(value);
        Console.ResetColor();
    }
}


